development:
  adapter: postgresql
  encoding: utf8
  database: snowday_development
  username: [username]
  password: [password]
  template: template_postgis # Required for spatial support

test:
  adapter: postgresql
  encoding: utf8
  database: snowday_test
  username: [username]
  password: [password]
  template: template_postgis # Required for spatial support

production:
  adapter: postgresql
  encoding: utf8
  database: snowday_production
  username: [username]
  password: [password]
  template: template_postgis # Required for spatial support